version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      ONLINE_MODE: "FALSE"
      SERVER_NAME: "LittleSaiGon"
      SEED: "-2895465341997673906"
      DIFFICULTY: "normal"
      VIEW_DISTANCE: "8"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      # attach a directory relative to the directory containing this compose file
      - minecraft_data:/data
volumes:
    minecraft_data:
